dir.create("data")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/c.geojson", destfile = "data/c.geojson")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/l.geojson", destfile = "data/l.geojson")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/rf.geojson", destfile = "data/rf.geojson")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/rq.geojson", destfile = "data/rq.geojson")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/rq.geojson", destfile = "data/rq.geojson")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/rnet.geojson", destfile = "data/rnet.geojson")
download.file(url = "https://github.com/npct/pct-outputs-regional/raw/master/commute/msoa/isle-of-wight/z.geojson", destfile = "data/z.geojson")
